return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		preset = "helix",
		icons = { mappings = true },
		spec = {
			{ "<leader>a", group = "AI (Claude Code)" },
			{ "<leader>b", group = "Buffer" },
			{ "<leader>d", group = "Debug" },
			{ "<leader>e", group = "Explore/Edit" },
			{ "<leader>f", group = "Find" },
			{ "<leader>g", group = "Git" },
			{ "<leader>gf", group = "Flow" },
			{ "<leader>gff", group = "Feature" },
			{ "<leader>gfr", group = "Release" },
			{ "<leader>gfh", group = "Hotfix" },
			{ "<leader>gfb", group = "Bugfix" },
			{ "<leader>l", group = "Language" },
			{ "<leader>n", group = "Notes (Obsidian)" },
			{ "<leader>o", group = "Other" },
			{ "<leader>r", group = "Replace" },
			{ "<leader>s", group = "Session" },
			{ "<leader>t", group = "Terminal" },
			{ "<leader>v", group = "Visits" },
		},
	},
}
