return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		preset = "helix",
		icons = { mappings = true },
		spec = {
			{ "<leader>a", group = "AI (Claude Code)" },
			{ "<leader>b", group = "Buffer" },
			{ "<leader>d", group = "Debug" },
			{ "<leader>e", group = "Explore/Edit", icon = " " },
			{ "<leader>f", group = "Find" },
			{ "<leader>g", group = "Git" },
			{ "<leader>gc", group = "Conflict", icon = "󰘬 " },
			{ "<leader>gf", group = "Flow", icon = " " },
			{ "<leader>gff", group = "Feature", icon = " " },
			{ "<leader>gfr", group = "Release", icon = " " },
			{ "<leader>gfh", group = "Hotfix", icon = " " },
			{ "<leader>gfb", group = "Bugfix", icon = " " },
			{ "<leader>l", group = "Language", icon = " " },
			{ "<leader>n", group = "Notes (Obsidian)", icon = " " },
			{ "<leader>o", group = "Other", icon = " " },
			{ "<leader>r", group = "Replace", icon = "󰛔 " },
			{ "<leader>s", group = "Session" },
			{ "<leader>t", group = "Terminal" },
			{ "<leader>v", group = "Visits", icon = "󰃀 " },
		},
	},
}
